### ISSUE TITLE
y_inline and Crashdetect

### ISSUE THREAD

**Issue by pds2k12** [Zeex/samp-plugin-crashdetect#33] opened 2014-07-05 19:12 UTC
I found out that <i>y_inline</i> isn't compatible with <i>crashdetect</i>, It took me hours to configure out what causes the crash (without any output from <i>crashdetect</i>) after hours of searching, I tried using normal compiler as I am using your compiler but using yours and normal compiler causes crash aswell, so I started suspecting on <i>plugins</i> after <i>trial</i> and <i>error</i> (removed <li>crashdetect</i>) the crash does not occur anymore so I am guessing the crash was caused by <i>crashdetect</i> 

```
[14:42:08] Number of vehicle models: 0
[14:42:32] Incoming connection: x.xx.xxx.xxx
[14:42:32] [join] pds2k12 has joined the server (0:x.xx.xxx.xxx)

- crash occurs here, no ouput from crash detect, or no message saying Server Shutting down, it loaded the log file.

----------
Loaded log file: "server_log.txt".
```

<b>NOTE</b>: I only experience this in Debian 7 or CentOS, I am not sure if it happens on other linux versions but it works perfectly on Windows 7.

**Comment by Zeex** [comment] 2015-03-02 12:46
I think this might be a duplicate of #38. Can you test you script with latest code from [amx_assembly](../../amx_assembly)?

**Comment by Zeex** [comment] 2015-03-30 07:41
Closing as duplicate of #38.

**Closed by Zeex** 2015-03-30 07:41 UTC
